worker_processes  auto;
events { worker_connections 1024; }

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            record all;
            record_path /tmp/recordings;
            record_unique on;

            exec_publish_done ffmpeg -i rtmp://localhost/live/$name -c copy -f mp4 /tmp/recordings/$name.mp4;
        }
    }
}

http {
    server {
        listen 80;
        listen [::]:80;

        server_name _;

        root /var/www/vhosts/web;
        index index.php;

        client_max_body_size 128M;

        # Timeout-Einstellungen
        client_body_timeout 600s;
        client_header_timeout 600s;
        keepalive_timeout 750s;
        send_timeout 600s;

        # Proxy-Timeout für Backends
        proxy_connect_timeout 600s;
        proxy_send_timeout 600s;
        proxy_read_timeout 600s;

        location @defaultRules {
            try_files index.php /index.php$is_args$args;
            rewrite ^(.*)$ /index.php?_url=$1 break;
        }


        location / {
            try_files $uri /index.php$is_args$args;
        }

        location /videos/ {
            alias /tmp/recordings/;
            autoindex on;
        }

        location ~ \.php$  {
            fastcgi_pass                    php-fpm-video-srv:9000;
            fastcgi_index                   index.php;
            fastcgi_split_path_info         ^(.+\.php)(.*)$;
            include                         fastcgi_params;
            fastcgi_param PATH_INFO         $fastcgi_path_info if_not_empty;
            fastcgi_param SCRIPT_FILENAME   $document_root$fastcgi_script_name;
            fastcgi_param SERVER_NAME       $server_name;
            fastcgi_param SERVER_NAME       $host;
        }

        # Timeout-Einstellungen für PHP-FPM
        fastcgi_connect_timeout 300s;
        fastcgi_send_timeout 300s;
        fastcgi_read_timeout 300s;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
    }
}
